package com.automataTheory;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Main {
    private static char character;
    private static Scanner in;
    private static StringBuilder buffer;
    private static StringBuilder tempVar;
    private static List<String> varList;
    private static StringBuilder varType;

    static {
        in = new Scanner(System.in).useDelimiter("");
        buffer = new StringBuilder();
        tempVar = new StringBuilder();
        varList = new ArrayList<>();
        varType = new StringBuilder();
    }

    public static void main(String[] args) {
        command();
        createFile();
    }

    private static void nextChar() {
        character = in.next().charAt(0);
        buffer.append(character);
    }

    private static void type() {
        if (character == 'c') {
            varType.append(character);
            nextChar();
            if (character == 'h') {
                varType.append(character);
                nextChar();
            } else {
                error("Expected letter 'h'!");
                System.exit(1);
            }
            if (character == 'a') {
                varType.append(character);
                nextChar();
            } else {
                error("Expected letter 'a'!");
                System.exit(1);
            }
            if (character == 'r') {
                varType.append(character);
                nextChar();
            } else {
                error("Expected letter 'r'!");
                System.exit(1);
            }
        } else if (character == 'i') {
            varType.append(character);
            nextChar();
            if (character == 'n') {
                varType.append(character);
                nextChar();
            } else {
                error("Expected letter 'n'!");
                System.exit(1);
            }
            if (character == 't') {
                varType.append(character);
                nextChar();
            } else {
                error("Expected letter 't'!");
                System.exit(1);
            }
        } else {
            error("Unsupported data type!");
            System.exit(1);
        }
    }

    private static void name() {
        if (Character.isAlphabetic(character)) {
            tempVar.append(character);
            nextChar();
        } else {
            error("Variable name does no start from a letter!");
            System.exit(1);
        }
        while (Character.isAlphabetic(character) || Character.isDigit(character)) {
            tempVar.append(character);
            nextChar();
        }
    }

    private static void constant() {
        if (character >= '1' && character <= '9') {
            tempVar.append(character);
            nextChar();
        } else {
            error("Variable value starts with number 0 or with letter!");
            System.exit(1);
        }
        while (character >= '0' && character <= '9') {
            tempVar.append(character);
            nextChar();
        }
    }

    private static void var() {
        name();
        if (character == '=') {
            tempVar.append("=");
            nextChar();
            constant();
        }
        varList.add(tempVar.toString());
        tempVar.setLength(0);
    }

    private static void command() {
        nextChar();
        type();
        if (Character.isWhitespace(character)) {
            nextChar();
        }
        var();
        while (character == ',') {
            nextChar();
            var();
        }
        if (character == ';') {
            System.out.println("The string was recognized successfully!");
        } else {
            error("Command end character expected ';'!");
            System.exit(1);
        }
    }

    private static String errorLocation() {
        return "Error at position: " +
                buffer +
                "\n" +
                " ".repeat(Math.max(0, buffer.length() + 18)) +
                '^';
    }

    private static void error(String errorMessage) {
        System.out.println(errorMessage + ":\n" + errorLocation());
    }

    private static String showVars() {
        String vars = String.join(",", varList);
        return varType.toString() + " " + vars + ";";
    }


    private static String createProgram() {
        // Example of a file text generated by the program.
        /*
        package com.company.secondExercise;

        import java.util.Scanner;

        public class Try {
            public static void main(String[] args) {
                Scanner in = new Scanner(System.in);

                char a,k=20,k1=90,b,ng=31;

                System.out.println("Enter the value of variable a:");
                a = (char)in.nextInt();
                System.out.println("Enter the value of variable b:");
                b = (char)in.nextInt();

                System.out.println("char a=" + (int)na);
                System.out.println("b=" + (int)b);
            }
        }
        */

        StringBuilder res = new StringBuilder();
        res.append("package com.automataTheory;\n" +
                "\n" +
                "import java.util.Scanner;\n" +
                "\n" +
                "public class Command {\n" +
                "    public static void main(String[] args) {\n" +
                "        Scanner in = new Scanner(System.in);\n" +
                "\n" +
                "        " + showVars() +
                "\n"
        );
        for (String s : varList) {
            if (!s.contains("=")) {
                res.append("        System.out.print(\"Enter the value of variable " + s + ":\");\n" +
                        "        " + s + " = ");
                if ("char".equals(varType.toString())) {
                    res.append("(char)");
                }
                res.append("in.nextInt();\n");
            }
        }

        for (String varName : varList) {
            int index = varName.indexOf('=');
            if (index != -1) {
                varName = varName.substring(0, index);
            }
            res.append("        System.out.println(\"" + varType + " " + varName + "=\" + ");
            if ("char".equals(varType.toString())) {
                res.append("(int)");
            }
            res.append(varName + ");\n");
        }

        res.append(
                "    }\n" +
                        "}");

        return res.toString();
    }


    private static void createFile() {
        try {
            File myObj = new File("src/main/java/com/automataTheory/Command.java");
            if (myObj.createNewFile()) {
                System.out.println("File created: " + myObj.getName());
            } else {
                System.out.println("The file has already been created.");
            }
        } catch (IOException e) {
            System.out.println("Error occurred.");
            e.printStackTrace();
        }

        try {
            FileWriter myWriter = new FileWriter("src/main/java/com/automataTheory/Command.java");
            myWriter.write(createProgram());
            myWriter.close();
            System.out.println("Writing to the file was successful.");
        } catch (IOException e) {
            System.out.println("Error occurred.");
            e.printStackTrace();
        }
    }
}